### ISSUE TITLE
Добавить requirements.txt

### ISSUE THREAD

**Issue by J3FALL** [Siella/ProFIT#6]
Сейчас в проекте нет файла requirements.txt, куда нужно занести список всех сторонних зависимостей (python-пакетов) и их версий. Это усложняет перенос кода на стороннее окружение, например, на мой ПК.
+ В если в дальнейшем планируется настраивать какой-то CI/CD (как минимум, для тестов), это в любом случае придется сделать.

Чтобы узнать, какие версии пакетов используются, можно воспользоваться утилитой [pipreqs](v).

**Comment by Siella** [comment]
Взяла на заметку, спасибо.

**Comment by J3FALL** [comment]
Этот файл лучше перенести в корневую папку проекта, т.к. по умолчанию утилиты типа pep ищут его там.
Да и в целом, кажется, все проекты, которые я видел на github, были так оформлены.

**Comment by Siella** [comment]
Хорошо, перенесу при следующем коммите.
