### ISSUE TITLE
Добавить gitignore

### ISSUE THREAD

**Issue by J3FALL** [Siella/ProFIT#7]
Сейчас в проекте нет файла .gitignore, который помогает фильтровать все временные/ненужные/системные файлы при коммитах.

Можно взять за основу пример этого файла [отсюда](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore) - это gitignore от Jetbrains для тех, кто использует их IDE.
При необходимости можно добавить какие-нибудь временные директории/файлы/etc, которые используются или создаются в проекте.

**Comment by Siella** [comment]
Добавила стандартный шаблон.
