### ISSUE TITLE
Инструкции How To Use в README

### ISSUE THREAD

**Issue by J3FALL** [Siella/ProFIT#9]
Сейчас в README есть ссылка на пример с jupyter-ноутбуком, как можно использовать фреймворк. Однако, это не всегда удобно, поскольку не все (например, я :) предпочитают их использовать, а хочется скопировать простой пример кода в свой скрипт и запустить его.
Предлагаю добавить в README отдельный раздел с примерами кода. Упрощенный, без формул и большого описания. 

Как я себе это представляю в первом приближении:

```python
import pandas as pd
from profit import ProcessMap
# load data from csv-file
monitoring = "../ProFIT/demo/log_examples/remote_monitoring.csv"
pd.read_csv(monitoring, encoding='cp1251').head()

# init ProcessMap and fit by monitoring data
pm = ProcessMap()
pm.set_log(monitoring, encoding='cp1251')
pm.set_rates(80, 5)
pm.set_params(optimize=False, aggregate=False)
pm.update()
pm.render()
```

**Comment by Siella** [comment]
Добавила в раздел demo
